title = "UniWebViewHelper"
file = "uniwebviewhelper"

[[Methods]]
name = "StreamingAssetURLForPath"
syntax = "StreamingAssetURLForPath(string path)"
returnType = "string"
summary = """
Get the local streaming asset path for a given file path related to the StreamingAssets folder.

This method will help you to concat a URL string for a file under your StreamingAssets folder for different platforms.
"""
example = """
```csharp
var url = UniWebViewHelper.StreamingAssetURLForPath("www/localHTML.html");
webView.Load(url);
```
"""
[[Methods.parameters]]
name = "path"
type = "string"
summary = """
The relative path to the Assets/StreamingAssets of your file. 

For example, if you placed a html file under `Assets/StreamingAssets/www/index.html`, you should pass `www/index.html` as parameter.
"""
[[Methods.badges]]
name = "static"
color = "blue"



[[Methods]]
name = "PersistentDataURLForPath"
syntax = "PersistentDataURLForPath(string path)"
returnType = "string"
summary = """
Get the local persistent data path for a given file path related to the data folder of your host app.

This method will help you to concat a URL string for a file under you stored in the `persistentDataPath`.
"""
example = """
```csharp
var url = UniWebViewHelper.PersistentDataURLForPath("www/index.html");
webView.Load(url);
```
"""
[[Methods.parameters]]
name = "path"
type = "string"
summary = """
The relative path to the Assets/StreamingAssets of your file.
"""
[[Methods.badges]]
name = "static"
color = "blue"
